### ISSUE TITLE
People are searching for this website. Project still alive?

### ISSUE THREAD

**Issue by bitkojine** [arewequantumyet/arewequantumyet.github.io#4]

**Comment by florianrein** [comment]
In general it is still alive, but it lives from the contribution of the ppl. :) If you have an interesting quantum computing-related framework for Rust, please feel free to open a PR. Otherwise Quantum is a comparably small field and few things change except for major and minor version updates. Here I have to prioritise since I have a few more projects.

So if you are missing something, please feel free to drop me a line [here](https://www.florianreinhard.de/kontakt/). I'm better reachable via mail.
